# Generated by Django 3.2 on 2021-04-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('Author_First', models.CharField(max_length=30)),
                ('Author_Last', models.CharField(max_length=30)),
            ],
        ),
    ]
